name: DragonHealthPlugin
version: 1.0.0
main: com.starmaster.dragonhealth.DragonHealthPlugin
api-version: 1.21
author: StarMaster
description: Easily customize the Ender Dragon's health for more challenging boss fights
website: https://modrinth.com/plugin/dragonhealthplugin

commands:
  dragonhealth:
    description: Reload dragon health configuration
    usage: /dragonhealth reload
    permission: dragonhealth.admin

permissions:
  dragonhealth.admin:
    description: Allows access to dragon health commands
    default: op